### PR TITLE
Account tooltip position updated

### PR DESCRIPTION
**Pull request by MonikaCat**
Fix for issue #238

### CODE REVIEW

**Comment by kwunyeung** [comment]
@MonikaCat is this not valid anymore as #238 was fixed in another PR?

**Comment by MonikaCat** [comment]
The tooltip has been updated, however, the positioning still requires fixing. Since this issue is closed, I have created a new one - #262 and will push it as soon as I can :)

**Comment by kwunyeung** [comment]
@MonikaCat so this PR is not valid any more? Should I close it?

**Comment by MonikaCat** [comment]
Yes, please. This PR is no longer valid as it has been replaced and fixed in PR #264 .

**Pull request closed without merging**
